// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdNEE1ZaIjvdF1l3K7XoD2kJu9fagEDY',
    appId: '1:117895636744:web:2559713aa3147db4eb2ebd',
    messagingSenderId: '117895636744',
    projectId: 'messagepractice-79eee',
    authDomain: 'messagepractice-79eee.firebaseapp.com',
    storageBucket: 'messagepractice-79eee.firebasestorage.app',
    measurementId: 'G-BZH66DG2QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtkcEl8YIhldFCBkiMy3KjYQKg0kFyuo',
    appId: '1:117895636744:android:3874fe40fe8b75edeb2ebd',
    messagingSenderId: '117895636744',
    projectId: 'messagepractice-79eee',
    storageBucket: 'messagepractice-79eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-atVjsVoIEE0wHb8K5VycS_fOUcFL4I',
    appId: '1:117895636744:ios:dcb61b7c795072d1eb2ebd',
    messagingSenderId: '117895636744',
    projectId: 'messagepractice-79eee',
    storageBucket: 'messagepractice-79eee.firebasestorage.app',
    iosBundleId: 'com.example.messagePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-atVjsVoIEE0wHb8K5VycS_fOUcFL4I',
    appId: '1:117895636744:ios:dcb61b7c795072d1eb2ebd',
    messagingSenderId: '117895636744',
    projectId: 'messagepractice-79eee',
    storageBucket: 'messagepractice-79eee.firebasestorage.app',
    iosBundleId: 'com.example.messagePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdNEE1ZaIjvdF1l3K7XoD2kJu9fagEDY',
    appId: '1:117895636744:web:7268a2bb45794e8beb2ebd',
    messagingSenderId: '117895636744',
    projectId: 'messagepractice-79eee',
    authDomain: 'messagepractice-79eee.firebaseapp.com',
    storageBucket: 'messagepractice-79eee.firebasestorage.app',
    measurementId: 'G-6PE63G4P69',
  );
}
